### ISSUE TITLE
Web Migration Error on Initial Service Start 

### ISSUE THREAD

**Issue by dennisfoconnor** [NREL/api-umbrella#154]
I've installed up api umbrella 0.8.0 on Amazon Linux 2015.03 from the RedHat EL6 RPM.
I have an external Mongo DB running v 3.0.4 with Auth Schema v5
I have mongo a user api-umbrella with the dbOwner role  on the api-umbrella database.
I can connect to the mongo database from the command line with the mongo client using the credentials.

The api-umbrella service fails to start.

Any help would be appreciated.

This is the output from /opt/api-umbrella/var/log/daemon.log:
```
Starting api-umbrella................. [FAIL]

{ [Error: web migration error: Command failed: rake aborted!
Moped::Errors::AuthenticationFailure: The operation: #<Moped::Protocol::Commands::Authenticate
  @length=162
  @request_id=3
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="api-umbrella.$cmd"
  @skip=0
  @limit=-1
  @selector={:authenticate=>1, :user=>"api-umbrella", :nonce=>"f91877d57cc6ba60", :key=>"689c062de885b3749437e5e4217ce4b9"}
  @fields=nil>
failed with error 18: "auth failed"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error./opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:505:in `login'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:57:in `block in apply_auth'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:56:in `each'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:56:in `apply_auth'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/cluster.rb:209:in `block in with_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:197:in `ensure_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/cluster.rb:208:in `with_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session/context.rb:108:in `with_node'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session/context.rb:56:in `insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/collection.rb:106:in `block in insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session.rb:324:in `with'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/collection.rb:105:in `insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/indexes.rb:58:in `create'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:30:in `block in create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:25:in `each_pair'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:25:in `create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:21:in `block in create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:18:in `each'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:18:in `create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/railties/database.rake:71:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:mongoid:create_indexes
(See full trace by running task with --trace)


STDOUT:

STDERR:rake aborted!
Moped::Errors::AuthenticationFailure: The operation: #<Moped::Protocol::Commands::Authenticate
  @length=162
  @request_id=3
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="api-umbrella.$cmd"
  @skip=0
  @limit=-1
  @selector={:authenticate=>1, :user=>"api-umbrella", :nonce=>"f91877d57cc6ba60", :key=>"689c062de885b3749437e5e4217ce4b9"}
  @fields=nil>
failed with error 18: "auth failed"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error./opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:505:in `login'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:57:in `block in apply_auth'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:56:in `each'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:56:in `apply_auth'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/cluster.rb:209:in `block in with_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:197:in `ensure_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/cluster.rb:208:in `with_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session/context.rb:108:in `with_node'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session/context.rb:56:in `insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/collection.rb:106:in `block in insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session.rb:324:in `with'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/collection.rb:105:in `insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/indexes.rb:58:in `create'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:30:in `block in create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:25:in `each_pair'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:25:in `create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:21:in `block in create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:18:in `each'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:18:in `create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/railties/database.rake:71:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:mongoid:create_indexes
(See full trace by running task with --trace)
] killed: false, code: 1, signal: null }
Error: web migration error: Command failed: rake aborted!
Moped::Errors::AuthenticationFailure: The operation: #<Moped::Protocol::Commands::Authenticate
  @length=162
  @request_id=3
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="api-umbrella.$cmd"
  @skip=0
  @limit=-1
  @selector={:authenticate=>1, :user=>"api-umbrella", :nonce=>"f91877d57cc6ba60", :key=>"689c062de885b3749437e5e4217ce4b9"}
  @fields=nil>
failed with error 18: "auth failed"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error./opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:505:in `login'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:57:in `block in apply_auth'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:56:in `each'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:56:in `apply_auth'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/cluster.rb:209:in `block in with_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:197:in `ensure_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/cluster.rb:208:in `with_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session/context.rb:108:in `with_node'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session/context.rb:56:in `insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/collection.rb:106:in `block in insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session.rb:324:in `with'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/collection.rb:105:in `insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/indexes.rb:58:in `create'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:30:in `block in create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:25:in `each_pair'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:25:in `create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:21:in `block in create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:18:in `each'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:18:in `create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/railties/database.rake:71:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:mongoid:create_indexes
(See full trace by running task with --trace)


STDOUT:

STDERR:rake aborted!
Moped::Errors::AuthenticationFailure: The operation: #<Moped::Protocol::Commands::Authenticate
  @length=162
  @request_id=3
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="api-umbrella.$cmd"
  @skip=0
  @limit=-1
  @selector={:authenticate=>1, :user=>"api-umbrella", :nonce=>"f91877d57cc6ba60", :key=>"689c062de885b3749437e5e4217ce4b9"}
  @fields=nil>
failed with error 18: "auth failed"

See https://github.com/mongodb/mongo/blob/master/docs/errors.md
for details about this error./opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:505:in `login'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:57:in `block in apply_auth'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:56:in `each'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:56:in `apply_auth'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/cluster.rb:209:in `block in with_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/node.rb:197:in `ensure_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/cluster.rb:208:in `with_primary'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session/context.rb:108:in `with_node'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session/context.rb:56:in `insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/collection.rb:106:in `block in insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/session.rb:324:in `with'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/collection.rb:105:in `insert'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/moped-1.5.2/lib/moped/indexes.rb:58:in `create'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:30:in `block in create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:25:in `each_pair'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/indexes.rb:25:in `create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:21:in `block in create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:18:in `each'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/rails/mongoid.rb:18:in `create_indexes'
/opt/api-umbrella/embedded/apps/web/shared/bundle/ruby/2.1.0/gems/mongoid-3.1.6/lib/mongoid/railties/database.rake:71:in `block (3 levels) in <top (required)>'
Tasks: TOP => db:mongoid:create_indexes
(See full trace by running task with --trace)

    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)

  See /opt/api-umbrella/var/log/supervisord-forever.log for more details

Stopping api-umbrella.... [  OK  ]
```

This is the contents of my /etc/api-umbrella/api-umbrella.yml file (credentials and hosts removed):
```YAML
default_host: hostname.com
elasticsearch:
  hosts:
  - http://elasticsearhhost.com:9200
hosts:
- default: true
  hostname: dev.api.hostname.com
mongodb:
  url: mongodb://api-umbrella:password@mongo.hostname.com:27000/api-umbrella
services:
- router
- web
site_name: SiteName
web:
  admin:
    initial_superusers:
    - user1@hostname.com
    - user2@hostname.com
    - user3@hostname.com
  mailer:
    smtp_settings:
      address: email-smtp.us-east-1.amazonaws.com
      authentication: plain
      enable_starttls_auto: true
      password: ses-password
      port: 587
      user_name: ses-username
```

**Comment by GUI** [comment]
I believe the issue is that the Ruby Mongo client doesn't support the newer [SCRAM-SHA-1](http://docs.mongodb.org/manual/release-notes/3.0-scram/) authentication that MongoDB 3.0 defaults to: https://github.com/mongoid/moped/issues/367 And unfortunately, judging from that issue, it doesn't seem like we'll be getting support anytime soon (at least with a simple patch release) since we're still on the Rails 3 versions of the Mongoid library (Mongoid 3.1 and Moped 1.5). We're working on some potential upgrades that would get us onto newer Mongo client libraries, which would solve this, but I don't have any concrete timelines for that yet.

In the meantime, if you do want to use MongoDB 3 plus authentication for your server, I think it might be possible with a bit of a workaround. This topic covers the details (since this issue has affected more than just the ruby moped client): https://jira.mongodb.org/browse/SERVER-17459 But basically, I think you'll need to run the commands referenced there to switch your auth schema back to v3. Then I believe you'll also need to re-create the API Umbrella user after that switch is made. As long as you don't then run the authentication upgrade process on your database, I think this should allow that user to exist with the older MONGODB-CR auth which should allow the ruby client to authenticate.

We haven't done any real testing of API Umbrella against MongoDB 3, so there may still be other issues with this combination. However, I do vaguely recall playing around with it briefly when MongoDB 3 first came out, and I think I was able to get API Umbrella spun up against it, and things generally worked, so hopefully there won't be too many more issues if you can workaround this authentication bit.

**Comment by dennisfoconnor** [comment]
I was able to work around the issue by using Mongo 2.6.10. 

Thank you.

**Comment by GUI** [comment]
Yeah, that's probably the simplest option (since that's the version we bundle and test against), but glad you were able to get it working. But this is definitely good to know about regarding potential incompatibility against Mongo 3. I'll keep it on our radar.
