### ISSUE TITLE
Rails Timeout publishing APIS

### ISSUE THREAD

**Issue by rogeriollacerda** [NREL/api-umbrella#264]
We have a python api to read our apis from consul and publish on api-umbrella. When we call publisher action by web interface, we get timeout error. 

`2016-07-14T15:58:20.74112 /opt/api-umbrella/embedded/lib/ruby/2.2.0/timeout.rb:88:in `block in timeout'
2016-07-14T15:58:20.74112 /opt/api-umbrella/embedded/lib/ruby/2.2.0/timeout.rb:98:in `call'
2016-07-14T15:58:20.74113 /opt/api-umbrella/embedded/lib/ruby/2.2.0/timeout.rb:98:in `timeout'
2016-07-14T15:58:20.74113 /opt/api-umbrella/embedded/apps/core/releases/20160630055831/vendor/bundle/ruby/2.2.0/gems/rack-timeout-0.0.4/lib/rack/timeout.rb:16:in `call'
2016-07-14T15:58:20.74113 /opt/api-umbrella/embedded/apps/core/releases/20160630055831/vendor/bundle/ruby/2.2.0/gems/railties-3.2.22.2/lib/rails/engine.rb:484:in `call'
2016-07-14T15:58:20.74114 /opt/api-umbrella/embedded/apps/core/releases/20160630055831/vendor/bundle/ruby/2.2.0/gems/railties-3.2.22.2/lib/rails/application.rb:231:in `call'
2016-07-14T15:58:20.74114 /opt/api-umbrella/embedded/apps/core/releases/20160630055831/vendor/bundle/ruby/2.2.0/gems/railties-3.2.22.2/lib/rails/railtie/configurable.rb:30:in `method_missing'
2016-07-14T15:58:20.74115 /opt/api-umbrella/embedded/apps/core/releases/20160630055831/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/configuration.rb:51:in `call'
2016-07-14T15:58:20.74115 /opt/api-umbrella/embedded/apps/core/releases/20160630055831/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:507:in `handle_request'
2016-07-14T15:58:20.74115 /opt/api-umbrella/embedded/apps/core/releases/20160630055831/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:375:in `process_client'
2016-07-14T15:58:20.74115 /opt/api-umbrella/embedded/apps/core/releases/20160630055831/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/server.rb:262:in `block in run'
2016-07-14T15:58:20.74116 /opt/api-umbrella/embedded/apps/core/releases/20160630055831/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `call'
2016-07-14T15:58:20.74116 /opt/api-umbrella/embedded/apps/core/releases/20160630055831/vendor/bundle/ruby/2.2.0/gems/puma-2.11.3/lib/puma/thread_pool.rb:104:in `block in spawn_thread'`

**Comment by GUI** [comment]
So to clarify, you've added API Backends to API Umbrella via the [Admin REST APIs](https://api-umbrella.readthedocs.io/en/latest/admin/api.html), and that worked successfully? But now you're hitting an error when trying to publish the API changes within the admin web interface after hitting the Publish button?

Based on these logs, I'm not exactly sure what's going on. But a couple things might help:

- Could you share more lines from the `/var/log/api-umbrella/web-puma/current` log file (preferably from the line beginning with `Started POST "/api-umbrella/v1/config/publish"...`)?
- Could you also share the contents from `/var/log/api-umbrella/nginx/access.log` and `/var/log/api-umbrella/nginx/current` from around the same time this error is generated?

Hopefully we'll then be able to pinpoint what's going on. Thanks!

**Comment by rogeriollacerda** [comment]
#266 Solved.
