### ISSUE TITLE
Unable to run vagrant up – Error executing action `create` on resource 'link[/vagrant/test/tmp/run]'

### ISSUE THREAD

**Issue by martinzuern** [NREL/api-umbrella#346]
When I tried to setup a dev environment, running vagrant up (after fixing [the vagrant-berkshelf issue](https://github.com/berkshelf/vagrant-berkshelf/issues/316)) failed with the following log:
```
==> default: * directory[/opt/api-umbrella-build/test/tmp/run] action create
==> default: [2017-03-23T16:22:48+00:00] INFO: directory[/opt/api-umbrella-build/test/tmp/run] created directory /opt/api-umbrella-build/test/tmp/run
==> default:     
==> default: - create new directory /opt/api-umbrella-build/test/tmp/run
==> default: [2017-03-23T16:22:49+00:00] INFO: directory[/opt/api-umbrella-build/test/tmp/run] owner changed to 500
==> default: [2017-03-23T16:22:49+00:00] INFO: directory[/opt/api-umbrella-build/test/tmp/run] group changed to 500
==> default: [2017-03-23T16:22:49+00:00] INFO: directory[/opt/api-umbrella-build/test/tmp/run] mode changed to 755
==> default:     
==> default: - change mode from '' to '0755'
==> default:     
==> default: - change owner from '' to 'vagrant'
==> default:     
==> default: - change group from '' to 'vagrant'
==> default: 
==> default: 
==> default:   
==> default: * directory[/vagrant/test/tmp/run] action delete
==> default:  (skipped due to only_if)
==> default:   
==> default: * link[/vagrant/test/tmp/run] action create
==> default:     
==> default: 
==> default:     
==> default: ================================================================================
==> default:     
==> default: Error executing action `create` on resource 'link[/vagrant/test/tmp/run]'
==> default:     
==> default: ================================================================================
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Errno::ENOENT
==> default:     
==> default: -------------
==> default:     
==> default: No such file or directory @ sys_fail2 - (/opt/api-umbrella-build/test/tmp/run, /vagrant/test/tmp/run)
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Cookbook Trace:
==> default:     
==> default: ---------------
==> default:     
==> default: /tmp/vagrant-chef/fd2d2394d7f1aa7819f27eae439180bd/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/fd2d2394d7f1aa7819f27eae439180bd/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/fd2d2394d7f1aa7819f27eae439180bd/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/fd2d2394d7f1aa7819f27eae439180bd/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
==> default: 
==> default:     
==> default: /tmp/vagrant-chef/fd2d2394d7f1aa7819f27eae439180bd/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Resource Declaration:
==> default:     
==> default: ---------------------
==> default:     
==> default: # In /tmp/vagrant-chef/fd2d2394d7f1aa7819f27eae439180bd/cookbooks/api-umbrella/recipes/development.rb
==> default: 
==> default:     
==> default: 
==> default: 
==> default:     
==> default:  79:   link "/vagrant/#{path}" do
==> default: 
==> default:     
==> default:  80:     to "/opt/api-umbrella-build/#{path}"
==> default: 
==> default:     
==> default:  81:   end
==> default: 
==> default:     
==> default:  82: end
==> default: 
==> default:     
==> default: 
==> default: 
==> default:     
==> default: Compiled Resource:
==> default:     
==> default: ------------------
==> default:     
==> default: # Declared in /tmp/vagrant-chef/fd2d2394d7f1aa7819f27eae439180bd/cookbooks/api-umbrella/recipes/development.rb:79:in `block in from_file'
==> default: 
==> default:     
==> default: 
==> default: 
==> default:     
==> default: link("/vagrant/test/tmp/run") do
==> default: 
==> default:       action [:create]
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       to "/opt/api-umbrella-build/test/tmp/run"
==> default:       link_type :symbolic
==> default:       target_file "/vagrant/test/tmp/run"
==> default:       declared_type :link
==> default:       cookbook_name :"api-umbrella"
==> default:       recipe_name "development"
==> default:     end
==> default:     
==> default: [2017-03-23T16:22:49+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: 
==> default: Running handlers:
==> default: [2017-03-23T16:22:49+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-03-23T16:22:49+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 18 resources updated in 16 seconds
==> default: [2017-03-23T16:22:49+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-03-23T16:22:49+00:00] ERROR: link[/vagrant/test/tmp/run] (api-umbrella::development line 79) had an error: Errno::ENOENT: No such file or directory @ sys_fail2 - (/opt/api-umbrella-build/test/tmp/run, /vagrant/test/tmp/run)
==> default: [2017-03-23T16:22:49+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

Running macOS 10.12.3
berkshelf-5.6.4
virtualbox 5.0.10

**Comment by GUI** [comment]
Sorry for the belated followup. I believe the Vagrant development environment should be fixed in master now (by https://github.com/NREL/api-umbrella-cookbook/commit/5c6b64bf31780b8e6a933ba00b32305a4a3f8960 and https://github.com/NREL/api-umbrella/commit/16967c3894dd2190f6ba158130cf1c90e37a73a8). So if you pull down the latest version of master of the api-umbrella repo and try `vagrant provision`, I believe this error should be fixed. But if you're still running into any issues, let us know.
