### ISSUE TITLE
POST /api-umbrella/v1/apis returns 500 Internal Server Error

### ISSUE THREAD

**Issue by avionwd** [NREL/api-umbrella#379]
I have installed API Umbrella via docker behind Nginx.
docker-compose.yml
```yml
srv:                                                                                                                                                               
  image: nrel/api-umbrella                                                                                                                                         
  volumes:                                                                                                                                                         
    - ./config:/etc/api-umbrella                                                                                                                                   
  ports:                                                                                                                                                           
    - 8180:8180                                                                                                                                                    
    - 8143:443
```

Nginx config
```
server {
        listen 80;
        server_name frontend.com;

        return 301 https://$host$request_uri;
}

server {
        listen 443 ssl;
        server_name frontend.com;

        include /etc/nginx/conf.d/_ssl;

        ssl_session_timeout  5m;

        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers   on;

        location / {
                proxy_pass https://localhost:8143;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-Port 443;
        }
}
```

When adding new API Backend in admin interface got 500 Internal Server Error.
In logs found error with CSRF token:
```
2017-08-04T08:52:03.38734 Started POST "/api-umbrella/v1/apis" for 193.239.254.187 at 2017-08-04 08:52:03 +0000
2017-08-04T08:52:03.38911 Processing by Api::V1::ApisController#create as JSON
2017-08-04T08:52:03.38924   Parameters: {"api"=>{"name"=>"mc", "sort_order"=>nil, "backend_protocol"=>"https", "frontend_host"=>"frontend.com", "backend_host"=>"backend.com", "balance_algorithm"=>"least_conn", "servers"=>[{"host"=>"backend.com", "port"=>443}], "url_matches"=>[{"sort_order"=>nil, "frontend_prefix"=>"/mc/", "backend_prefix"=>"/"}], "settings"=>{"require_https"=>nil, "disable_api_key"=>nil, "api_key_verification_level"=>nil, "rate_limit_mode"=>nil, "error_templates"=>{}, "error_data_yaml_strings"=>{}, "rate_limits"=>nil}, "sub_settings"=>nil, "rewrites"=>nil}}
2017-08-04T08:52:03.38941 Can't verify CSRF token authenticity
2017-08-04T08:52:33.38671 source=rack-timeout id=634d72d01876f168de7b7ad9a60be77f timeout=30000ms service=30000ms state=timed_out at=error
2017-08-04T08:52:33.38775 Completed 500 Internal Server Error in 29998ms
2017-08-04T08:52:33.39008 
2017-08-04T08:52:33.39010 Rack::Timeout::RequestTimeoutException (Request ran for longer than 30000ms):
2017-08-04T08:52:33.39011   app/models/api/server.rb:32:in `validate_host_resolves'
2017-08-04T08:52:33.39012   app/models/api.rb:306:in `save'
2017-08-04T08:52:33.39014   app/controllers/api/v1/apis_controller.rb:84:in `save!'
2017-08-04T08:52:33.39015   app/controllers/api/v1/apis_controller.rb:42:in `create'
2017-08-04T08:52:33.39016   app/controllers/application_controller.rb:160:in `set_userstamp'
2017-08-04T08:52:33.39017   app/controllers/application_controller.rb:88:in `block in use_locale'
2017-08-04T08:52:33.39018   app/controllers/application_controller.rb:87:in `use_locale'
2017-08-04T08:52:33.39018 
2017-08-04T08:52:33.39019
```

**Comment by ejames17** [comment]
having the same issue for outgoing mail
