### ISSUE TITLE
embedded elasticsearch heap space configuration

### ISSUE THREAD

**Issue by yanngv29** [NREL/api-umbrella#422]
using api-umbrella for some month, and now i got some problems with the analytics parts. The problem come from the embedded elasticsearch : 

```
2018-09-12T07:11:33.42320 RemoteTransportException[[Numinus][127.0.0.1:14003][indices:data/read/search[phase/query]]]; nested: ElasticsearchException[ElasticsearchException[java.lang.OutOfMemoryError: Java heap space]; nested: ExecutionError[java.lang.OutOfMemoryError: Java heap space]; nested: OutOfMemoryError[Java heap space];]; nested: UncheckedExecutionException[ElasticsearchException[java.lang.OutOfMemoryError: Java heap space]; nested: ExecutionError[java.lang.OutOfMemoryError: Java heap space]; nested: OutOfMemoryError[Java heap space];]; nested: ElasticsearchException[java.lang.OutOfMemoryError: Java heap space]; nested: ExecutionError[java.lang.OutOfMemoryError: Java heap space]; nested: OutOfMemoryError[Java heap space];
2018-09-12T07:11:33.42321 Caused by: ElasticsearchException[ElasticsearchException[java.lang.OutOfMemoryError: Java heap space]; nested: ExecutionError[java.lang.OutOfMemoryError: Java heap space]; nested: OutOfMemoryError[Java heap space];]; nested: UncheckedExecutionException[ElasticsearchException[java.lang.OutOfMemoryError: Java heap space]; nested: ExecutionError[java.lang.OutOfMemoryError: Java heap space]; nested: OutOfMemoryError[Java heap space];]; nested: ElasticsearchException[java.lang.OutOfMemoryError: Java heap space]; nested: ExecutionError[java.lang.OutOfMemoryError: Java heap space]; nested: OutOfMemoryError[Java heap space];
2018-09-12T07:11:33.42321 	at org.elasticsearch.index.fielddata.plain.AbstractIndexOrdinalsFieldData.loadGlobal(AbstractIndexOrdinalsFieldData.java:91)
2018-09-12T07:11:33.42322 	at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals$FieldData.globalOrdinalsValues(ValuesSource.java:144)
2018-09-12T07:11:33.42322 	at org.elasticsearch.search.aggregations.support.ValuesSource$Bytes$WithOrdinals.globalMaxOrd(ValuesSource.java:117)
2018-09-12T07:11:33.42322 	at org.elasticsearch.search.aggregations.bucket.terms.TermsAggregatorFactory.doCreateInternal(TermsAggregatorFactory.java:217)
2018-09-12T07:11:33.42323 	at org.elasticsearch.search.aggregations.support.ValuesSourceAggregatorFactory.createInternal(ValuesSourceAggregatorFactory.java:64)
2018-09-12T07:11:33.42323 	at org.elasticsearch.search.aggregations.AggregatorFactory.create(AggregatorFactory.java:102)
2018-09-12T07:11:33.42323 	at org.elasticsearch.search.aggregations.AggregatorFactories.createTopLevelAggregators(AggregatorFactories.java:87)
2018-09-12T07:11:33.42323 	at org.elasticsearch.search.aggregations.AggregationPhase.preProcess(AggregationPhase.java:85)
2018-09-12T07:11:33.42324 	at org.elasticsearch.search.query.QueryPhase.execute(QueryPhase.java:111)
2018-09-12T07:11:33.42324 	at org.elasticsearch.search.SearchService.loadOrExecuteQueryPhase(SearchService.java:372)
2018-09-12T07:11:33.42324 	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:385)
```

using ps command i saw that elasticsearch is running with thoses args :

`/usr/bin/java -Xms512m -Xmx512m -Djava.awt.headless=true -.....`

- i try to create a jvm.options file is the elasticsearch config directory,
- i try to set the ES_JAVA_OPTS in the .profile of my apiumbrella user,
- i read api_umbrella documentation,

but i can't find any way to make it work ...

**How can i change the -Xms -Xmx value for the embedded elastisearch inside the api umbrella solution ?**

**Comment by Buminta** [comment]
api-umbrella.yml

```
elasticsearch:
  embedded_server_config:
    network:
      host: 0.0.0.0
    node:
      master: true
      name: Umbrella-Master
  embedded_server_env:
    heap_size: 1G
```
